on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - id: gostep
        uses: dsp-testing/github-go-script@main
        with:
          dir: .github/workflows/awesome

      - run: echo $REPOSITORY_NAME
        env:
          REPOSITORY_NAME: ${{ steps.gostep.outputs.repository_name }}
